# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44e0094245a214377201036d71914a144117b0292ebbadc74633aafdf638c65529aa8491b320ffd59050e7fdbddea29e66f08a48b3c7da2c5ec9424edee7d83a

test:
  secret_key_base: 525499b8c188e9957845925d4db827c2724ebe9becf8eb65577f25844037910db03cd63069675eb55bd4e26062d20ab2bf08299711688f275d0243729ab6b365

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
